ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.280"
    hooks:
      - id: ruff
        args: [--fix, --ignore=E741, --exclude=__init__.py]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-ruff
        additional_dependencies: [ruff==0.0.280]
        args: ["--fix","--ignore=E501,E402"]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.15.0"
    hooks:
       - id: blacken-docs
         additional_dependencies: [black==22.12.0]
