[build-system]
requires = ["setuptools", "wheel", "cmake"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "pybamm"
description = "Python Battery Mathematical Modelling."
readme = { file = "README.md", content-type = "text/markdown" }
keywords = [
  "pybamm",
]
license = "OSI Approved :: BSD License"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
]
dynamic = [
  "version",
]
dependencies = [
    "numpy>=1.16",
    "scipy>=1.3",
    "pandas>=0.24",
    "casadi>=3.6.0",
    "xarray"
]

[project.optional-dependencies]
docs = [
    "sphinx>=1.5",
    "pydata-sphinx-theme",
    "sphinx_design",
    "sphinx-copybutton",
    "myst-parser",
    "sphinx-inline-tabs",
]
examples = [
    "pre-commit",
    "black",
    "jupyter",
]
plot = [
    "imageio>=2.9.0",
    "matplotlib>=2.0",
]
cite = [
    "pybtex>=0.24.0",
]
latexify = [
    "sympy>=1.8",
]
bpx = [
    "bpx",
]
tqdm = [
    "tqdm",
]
dev = [
    "numpy>=1.16",
    "scipy>=1.3",
    "pandas>=0.24",
    "anytree>=2.4.3",
    "autograd>=1.2",
    "scikit-fem>=0.2.0",
    "casadi>=3.6.0",
    "imageio>=2.9.0",
    "pybtex>=0.24.0",
    "sympy>=1.8",
    "xarray",
    "bpx",
    "tqdm",
    "matplotlib>=2.0",
]
all = [
    "numpy>=1.16",
    "scipy>=1.3",
    "pandas>=0.24",
    "anytree>=2.4.3",
    "autograd>=1.2",
    "scikit-fem>=0.2.0",
    "casadi>=3.6.0",
    "imageio>=2.9.0",
    "pybtex>=0.24.0",
    "sympy>=1.8",
    "xarray",
    "bpx",
    "tqdm",
    "matplotlib>=2.0",
    "sphinx>=1.5",
    "pydata-sphinx-theme",
    "sphinx_design",
    "sphinx-copybutton",
    "myst-parser",
    "sphinx-inline-tabs",
    "pre-commit",
    "black",
    "jupyter",
]